### ISSUE TITLE
opam install oml fails

### ISSUE THREAD

**Issue by Tyruiop** [rleonid/oml#151]
Hi!
I'm having the following problem when running opam install oml and I can't find a way to solve it, output is [here](https://tyruiop.org/~tyruiop/install_res.txt). Any idea how to solve it?

**Comment by struktured** [comment]
I think the oml opam package is broken because lacaml changed its api. @rleonid spent some time the last week preparing a new release to resolve the api changes. A work around is you could manually downgrade lacaml with something like `opam install lacaml.7.2.6 oml.0.0.5`, or you can try getting the master branch to compile (requires https://github.com/rleonid/dsfo).

**Comment by Tyruiop** [comment]
Worked perfectly, thanks a lot!

**Comment by dsheets** [comment]
If you know the `lacaml` version constraint, could you contribute it back to `ocaml/opam-repository`, please?

**Comment by rleonid** [comment]
@Tyruiop Once the constraints are in place (here and in opam) are there are other issues with installing `oml`?

**Comment by Tyruiop** [comment]
@rleonid as far as I can tell, the constrain for lacaml needs to be <= 7.6.2, not = 8.0.6. Also, I don't think it should require dsfo until it gets in opam

**Comment by rleonid** [comment]
@Tyruiop  My apologies for the confusion.  The constraints are on the `master` branch of oml, not the tagged versions in `opam`, their purpose is so that `oml` can build "right now".  `dsfo` is also only necessary for testing, and can easily be pinned directly to the github [repo](https://github.com/rleonid/dsfo).

**Comment by Tyruiop** [comment]
@rleonid my bad. From git, it builds fine here even with the last version of lacaml.

**Comment by rleonid** [comment]
Glad that we resolved it, happy to hear about any other feedback on oml.
