### ISSUE TITLE
repetition in the documentation of the API

### ISSUE THREAD

**Issue by vd1** [rleonid/oml#187]
here: http://www.hammerlab.org/oml/Uncategorized.Functions.html
there is a repetition in the text:

> Implementations of special functions such as those needed to compute probability distributions.
> 
> At the present moment many functions are wrappers to the Cephes library (http://www.netlib.org/cephes/), via a Ctypes interface implemented in the Ocephes library.
> 
> Implementations of special functions such as those needed to compute probability distributions.
> 
> At the present moment many functions are wrappers to the Cephes library (http://www.netlib.org/cephes/), via a Ctypes interface implemented in the Ocephes library.
>

**Comment by rleonid** [comment]
Thank you for bringing this to my attention. Since this error seems to stem from a vagary of `ocamldoc` and my own custom hacking to setup the `mli` for input, I'll try to and make sure that it is resolved when I release and update the docs for 0.0.7.

**Comment by vd1** [comment]
+1

**Comment by rleonid** [comment]
@vd1 The latest documentation for `Functions` in [Oml_full](http://www.hammerlab.org/oml/Oml_full.Statistics.Functions.html) unfortunately still has a duplication. In order to create decent documentation, I'm unfortunately forced to munge the contents of `mli` files inside of each other as at the moment there isn't a way to tell `ocamldoc` to grab the documentation from an `include`d module or module type. The duplicate comment comes from the `oml_functions` that is included inside of `omlf_functions`. Without sacrificing the comment there or special casing some smarter/hack I'd prefer to leave it there.
